
site_name: XAPI doc
site_url: https://x-venture.io/
theme:
  name: material
  logo: assets/xv-logo.png
extra_css: 
  - stylesheets/extra.css
  


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

#  features: header.autohide
nav:
    - Home: index.md
    - About: about.md
    - Getting Started : gettingStarted.md
    - 'Outsourcing links': 'https://google.com/'
    - Navigation: nav.md